### Login
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "imron",
  "password": "123456"
}

### Get users
GET http://localhost:3000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg4MjEyNTYzLCJleHAiOjE2ODgzODUzNjN9.MEmU0n12sq-OUHwN-DsQs7H1N9QAQqAFNrDRHXL8qbE


### Get single user
GET http://localhost:3000/users/3